---
# tasks file for preconfig
- name: Copy hosts
  copy:
    src: hosts
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0644'
    backup: yes
- name: Change repository
  shell: sed -i 's/archive.ubuntu.com/mirror.yandex.ru/g' /etc/apt/sources.list
- name: Update
  apt:
    update_cache: true
    # upgrade: true
    # cache_valid_time: 3600
- name: Wait 20
  wait_for: 
    timeout: 20    
# - name: Upgrade
#   apt: 
#     upgrade: true
# - name: Wait 20
#   wait_for: 
#     timeout: 20